sudo: required
language: python
services:
  - docker
install:
  - pip install ansible==2.3.2
  - pip install molecule==1.25.0
  - pip install docker
script:
  - molecule syntax
  - molecule create
  - molecule converge
  - molecule idempotence
  - molecule verify
  - molecule destroy
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$([[ "$TRAVIS_COMMIT_MESSAGE" == "Merge pull request.*/feature.*" ]] && git describe --abbrev=0 --tags | awk -F '.' '{print $1"."($2+1)"."0}' || git describe --abbrev=0 --tags | awk -F '.' '{print $1"."$2"."($3+1)}')
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
deploy:
  provider: script
  skip_cleanup: true
  script: git push https://${GH_TOKEN}:@github.com/SoInteractive/tests.git --tags
  on:
    branch: master
branches:
  except:
    - /^\d+\.\d+\.\d+$/